// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTCUWsg9C6bEqblMlcb5BCoY_mZzimC6c',
    appId: '1:349452993481:web:104720203e4032196c5e18',
    messagingSenderId: '349452993481',
    projectId: 'auticare-10677',
    authDomain: 'auticare-10677.firebaseapp.com',
    storageBucket: 'auticare-10677.firebasestorage.app',
    measurementId: 'G-24CLTF8Z0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6x596ESJWVodpzChKM2cZbmu39LHniM',
    appId: '1:349452993481:android:7f06b6f160cc90856c5e18',
    messagingSenderId: '349452993481',
    projectId: 'auticare-10677',
    storageBucket: 'auticare-10677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWY6PJkDj00fPuEE174IrrWlYPsIJ9Nk',
    appId: '1:349452993481:ios:261dafd5ad342e346c5e18',
    messagingSenderId: '349452993481',
    projectId: 'auticare-10677',
    storageBucket: 'auticare-10677.firebasestorage.app',
    iosBundleId: 'com.example.auticare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWY6PJkDj00fPuEE174IrrWlYPsIJ9Nk',
    appId: '1:349452993481:ios:261dafd5ad342e346c5e18',
    messagingSenderId: '349452993481',
    projectId: 'auticare-10677',
    storageBucket: 'auticare-10677.firebasestorage.app',
    iosBundleId: 'com.example.auticare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTCUWsg9C6bEqblMlcb5BCoY_mZzimC6c',
    appId: '1:349452993481:web:00a58631694f63236c5e18',
    messagingSenderId: '349452993481',
    projectId: 'auticare-10677',
    authDomain: 'auticare-10677.firebaseapp.com',
    storageBucket: 'auticare-10677.firebasestorage.app',
    measurementId: 'G-3XEKE2FRG7',
  );
}
